version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge